linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (io.Closer).Close
      - os.Remove
      - os.RemoveAll
      - net/http.ResponseWriter.Write
